# This template will create the initial Secret for the application. If it already exists, it will not overwrite the values.
# It will also not be deleted when the Helm release is deleted.

{{- if not (lookup "v1" "Secret" .Release.Namespace (include "app.fullname" .)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}
  labels: {{ include "app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  SECRET_KEY: {{ randAlphaNum 32 | b64enc }}
{{- end }}