volumes:
  postgis:
    driver: local

services:
  db:
    env_file: .env
    image: postgis/postgis:15-3.3-alpine
    container_name: ride-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgis:/var/lib/postgresql/data

  webapp:
    env_file: .env

    build:
      context: .
      dockerfile: ./compose/webapp/Dockerfile
      args:
        DEBUG_BUILD: true

    volumes:
      - ./src/webapp:/app/webapp

    stdin_open: true
    tty: true
    depends_on:
      - db
    container_name: webapp
    ports:
      - "8000:8000"
    command: /start.sh
    networks:
      - ride

  frontend:
    env_file: .env
    container_name: frontend
    build:
      context: ./
      dockerfile: ./compose/frontend/Dockerfile
      args:
        DEBUG_BUILD: true
    stdin_open: true
    tty: true
    ports:
      - "5173:5173"
    volumes:
      - ./src/frontend:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
      - /app/.react-router
    command: /bin/sh -c 'cd /app && npm run dev'
    # command: /bin/sh -c 'cd /app && npm run dev'
    # command: node

networks:
  ride:
    name: ride_default
    external: true