export const TrafficImpacts = [
  { id: 0, label: '' },
  { id: 1, label: 'Adverse weather (Ferries)' },
  { id: 2, label: 'All lanes blocked' },
  { id: 3, label: 'Assessment in progress' },
  { id: 4, label: 'Bridge closed (Traffic Pattern)' },
  { id: 5, label: 'Centre lane blocked' },
  { id: 6, label: 'Centre lane closed' },
  { id: 7, label: 'Centre lane closed in both directions' },
  { id: 8, label: 'Closed' },
  { id: 9, label: 'Closed ahead' },
  { id: 10, label: 'Closed for repairs' },
  { id: 11, label: 'Closed for the season' },
  { id: 12, label: 'Closed intermittently' },
  { id: 13, label: 'Closed to all traffic except emergency vehicles' },
  { id: 14, label: 'Crewing issues (Ferries)' },
  { id: 15, label: 'Debris in water (Ferries)' },
  { id: 16, label: 'Detour in effect' },
  { id: 17, label: 'Eastbound lane closure' },
  { id: 18, label: 'Emergency vehicles on scene' },
  { id: 19, label: 'Entrance ramp closed' },
  { id: 20, label: 'Essential Travel Only' },
  { id: 21, label: 'Estimated time of opening not available' },
  { id: 22, label: 'Exit ramp closed' },
  { id: 23, label: 'Expect Delays' },
  { id: 24, label: 'Expect Major delays due to congestion' },
  { id: 25, label: 'Expect Minor Delays' },
  { id: 26, label: 'Expect delay 20 (Ferries)' },
  { id: 27, label: 'Expect delay 30 (Ferries)' },
  { id: 28, label: 'Expect delay 40 (Ferries)' },
  { id: 29, label: 'Expect delay 50 (Ferries)' },
  { id: 30, label: 'Expect delay 60-90 (Ferries)' },
  { id: 31, label: 'Expect delay >90 (Ferries)' },
  { id: 32, label: 'Expect delays due to congestion' },
  { id: 33, label: 'Expect major delays' },
  { id: 34, label: 'Ferry Closed (Ferries)' },
  { id: 35, label: 'Ferry operating 24hrs (Ferries)' },
  { id: 36, label: 'Freshet (Ferries)' },
  { id: 37, label: 'HOV Lane Closed' },
  { id: 38, label: 'Heavy Congestion' },
  { id: 39, label: 'High river current (Ferries)' },
  { id: 40, label: 'High traffic volume (Ferries)' },
  { id: 41, label: 'Highway closure (Ferries)' },
  { id: 42, label: 'Lane Closure' },
  { id: 43, label: 'Lane blocked' },
  { id: 44, label: 'Lane closures in both directions' },
  { id: 45, label: 'Left lane blocked' },
  { id: 46, label: 'Left lane closed' },
  { id: 47, label: 'Left lane closed in both directions' },
  { id: 48, label: 'Left shoulder closed' },
  { id: 49, label: 'Left turn lane closed' },
  { id: 50, label: 'Marine traffic (Ferries)' },
  { id: 51, label: 'Mechanical issue (Ferries)' },
  { id: 52, label: 'Medical emergency (Ferries)' },
  { id: 53, label: 'Minor congestion' },
  { id: 54, label: 'No detour available' },
  { id: 55, label: 'Northbound lane closure' },
  { id: 56, label: 'On-ramp Shift' },
  { id: 57, label: 'Open to traffic' },
  { id: 58, label: 'Operational delay (Ferries)' },
  { id: 59, label: 'Paving operations' },
  { id: 60, label: 'Plowing and sanding' },
  { id: 61, label: 'Possible Delays' },
  { id: 62, label: 'Possible delays due to heavy traffic volumes' },
  { id: 63, label: 'Possible ferry delays (ferries)' },
  { id: 64, label: 'Ramp blocked' },
  { id: 65, label: 'Reduced to one lane' },
  { id: 66, label: 'Reduced to two lanes' },
  { id: 67, label: 'Replacement vessel (Ferries)' },
  { id: 68, label: 'Required maintenance (Ferries)' },
  { id: 69, label: 'Right lane blocked' },
  { id: 70, label: 'Right lane closed' },
  { id: 71, label: 'Right lane closed in both directions' },
  { id: 72, label: 'Right lane of exit ramp closed' },
  { id: 73, label: 'Right turn lane closed' },
  { id: 74, label: 'Road closure' },
  { id: 75, label: 'Road open' },
  { id: 76, label: 'Safety drills (Ferries)' },
  { id: 77, label: 'Safety inspection (Ferries)' },
  { id: 78, label: 'Sailing Cancellation (ferries)' },
  { id: 79, label: 'Sanded' },
  { id: 80, label: 'Schedule Modification (ferries)' },
  { id: 81, label: 'Seasonal Shutdown(Ferries)' },
  { id: 82, label: 'Seasonal shutdown (Ferries)' },
  { id: 83, label: 'Shoulder closed' },
  { id: 84, label: 'Single lane alternating traffic' },
  { id: 85, label: 'Slow down and drive to winter conditions' },
  { id: 86, label: 'Southbound lane closure' },
  { id: 87, label: 'Traffic signal out' },
  { id: 88, label: 'Truck lane available for all vehicles' },
  { id: 89, label: 'Truck restriction' },
  { id: 90, label: 'Two centre lanes blocked' },
  { id: 91, label: 'Two centre lanes closed' },
  { id: 92, label: 'Two left lanes blocked' },
  { id: 93, label: 'Two left lanes of exit ramp blocked' },
  { id: 94, label: 'Two right lanes blocked' },
  { id: 95, label: 'Two right lanes of exit ramp blocked' },
  { id: 96, label: 'Watch for traffic control' },
  { id: 97, label: 'Westbound lane closure' },
];

export const RestrictionsList = [
  { id: 0, label: '', },
  { id: 1, label: 'Axle Count', },
  { id: 2, label: 'Delay', },
  { id: 3, label: 'Height', },
  { id: 4, label: 'Length', },
  { id: 5, label: 'Speed Limit', },
  { id: 6, label: 'Speed Limit Advisory', },
  { id: 7, label: 'Speed Limit Truck', },
  { id: 8, label: 'Weight axle', },
  { id: 9, label: 'Weight vehicle', },
  { id: 10, label: 'Width', },
];

export const RoadConditions = [
  { id: 0, label: '', },
  { id: 1, label: 'Black ice', },
  { id: 2, label: 'Compact ice', },
  { id: 3, label: 'Slippery sections', },
  { id: 4, label: 'Slushy sections', },
  { id: 5, label: 'Compact snow', },
  { id: 6, label: 'High flood warning', },
  { id: 7, label: 'Sanded', },
  { id: 8, label: 'Plowing and sanding', },
  { id: 9, label: 'Muddy Sections', },
  { id: 10, label: 'Fog patches', },
  { id: 11, label: 'Heavy slush', },
  { id: 12, label: 'Water pooling', },
  { id: 13, label: 'Slushy Sections', },
  { id: 14, label: 'Slushy with slippery sections', },
  { id: 15, label: 'Rain on compact snow', },
  { id: 16, label: 'Debris on road', },
  { id: 17, label: 'Bridge Closed (Road Condition)', },
];

export const IncidentsList = [
  { id: 0, label: '', },
  { id: 1, label: '1 sailing wait (Ferries)', },
  { id: 2, label: '2 sailing wait (Ferries)', },
  { id: 3, label: '3 sailing wait (Ferries)', },
  { id: 4, label: '4 sailing wait (Ferries)', },
  { id: 5, label: '5-6 sailing wait (Ferries)', },
  { id: 6, label: '> 6 sailing wait (Ferries)', },
  { id: 7, label: 'Adverse weather (Ferries)', },
  { id: 8, label: 'Adverse weather (Ferries)', },
  { id: 9, label: 'Avalanche', },
  { id: 10, label: 'Avalanche control activities', },
  { id: 11, label: 'Avalanche Deposit Removal', },
  { id: 12, label: 'Avalanche Hazard', },
  { id: 13, label: 'Behind schedule >90 (Ferries)', },
  { id: 14, label: 'Behind schedule 20 (Ferries)', },
  { id: 15, label: 'Behind schedule 30 (Ferries)', },
  { id: 16, label: 'Behind schedule 40 (Ferries)', },
  { id: 17, label: 'Behind schedule 50 (Ferries)', },
  { id: 18, label: 'Behind schedule 60-90 (Ferries)', },
  { id: 19, label: 'Bridge closed', },
  { id: 20, label: 'Bridge damage', },
  { id: 21, label: 'Bridge wash out', },
  { id: 22, label: 'Cleared', },
  { id: 23, label: 'Collision', },
  { id: 24, label: 'Collision (closed)', },
  { id: 25, label: 'Crewing issues (Ferries)', },
  { id: 26, label: 'Crewing issues (Ferries)', },
  { id: 27, label: 'Debris in water (Ferries)', },
  { id: 28, label: 'Debris on road', },
  { id: 29, label: 'Delayed departure (Ferries)', },
  { id: 30, label: 'Delays >90 (Ferries)', },
  { id: 31, label: 'Expect delay >90 (Ferries)', },
  { id: 32, label: 'Expect delay 20 (Ferries)', },
  { id: 33, label: 'Expect delay 30 (Ferries)', },
  { id: 34, label: 'Expect delay 40 (Ferries)', },
  { id: 35, label: 'Expect delay 50 (Ferries)', },
  { id: 36, label: 'Expect delay 60-90 (Ferries)', },
  { id: 37, label: 'Falling ice', },
  { id: 38, label: 'Falling rock', },
  { id: 39, label: 'Ferry operating 24hrs (Ferries)', },
  { id: 40, label: 'Fire Travel Advisory - Special Incident', },
  { id: 41, label: 'Flooded', },
  { id: 42, label: 'Forest Fire', },
  { id: 43, label: 'Freshet (Ferries)', },
  { id: 44, label: 'Freshet (Ferries)', },
  { id: 45, label: 'Grass Fire', },
  { id: 46, label: 'Hazardous materials', },
  { id: 47, label: 'High avalanche hazard', },
  { id: 48, label: 'High river current (Ferries)', },
  { id: 49, label: 'High traffic volume (Ferries)', },
  { id: 50, label: 'Highway closure (Ferries)', },
  { id: 51, label: 'Hydro lines down', },
  { id: 52, label: 'Industrial Traffic', },
  { id: 53, label: 'Landslide', },
  { id: 54, label: 'Limited visibility', },
  { id: 55, label: 'Livestock warning', },
  { id: 56, label: 'Marine traffic (Ferries)', },
  { id: 57, label: 'Material spill', },
  { id: 58, label: 'Mechanical issue (Ferries)', },
  { id: 59, label: 'Mechanical issue (Ferries)', },
  { id: 60, label: 'Medical emergency (Ferries)', },
  { id: 61, label: 'Medical emergency (Ferries)', },
  { id: 62, label: 'Mudslide', },
  { id: 63, label: 'Multi-vehicle Incident', },
  { id: 64, label: 'Obstruction on roadway', },
  { id: 65, label: 'Operational delay (Ferries)', },
  { id: 66, label: 'Police incident', },
  { id: 67, label: 'Possible ferry delays (Ferries)', },
  { id: 68, label: 'Railway crossing incident', },
  { id: 69, label: 'Replacement vessel (Ferries)', },
  { id: 70, label: 'Required maintenance (Ferries)', },
  { id: 71, label: 'Required maintenance (Ferries)', },
  { id: 72, label: 'Rest area closed', },
  { id: 73, label: 'Rock slide', },
  { id: 74, label: 'Rocks on Road', },
  { id: 75, label: 'Safety drills (Ferries)', },
  { id: 76, label: 'Safety drills (Ferries)', },
  { id: 77, label: 'Safety inspection (Ferries)', },
  { id: 78, label: 'Safety inspection (Ferries)', },
  { id: 79, label: 'Sailing wait at East Side (Ferries)', },
  { id: 80, label: 'Sailing wait at East Terminal (Ferries)', },
  { id: 81, label: 'Sailing wait at North Bank (Ferries)', },
  { id: 82, label: 'Sailing wait at North Terminal (Ferries)', },
  { id: 83, label: 'Sailing wait at South Bank (Ferries)', },
  { id: 84, label: 'Sailing wait at South Terminal (Ferries)', },
  { id: 85, label: 'Sailing wait at West Side (Ferries)', },
  { id: 86, label: 'Sailing wait at West Terminal (Ferries)', },
  { id: 87, label: 'Seasonal shutdown (Ferries)', },
  { id: 88, label: 'Seasonal shutdown (Ferries)', },
  { id: 89, label: 'Seasonal Shutdown(Ferries)', },
  { id: 90, label: 'State of Emergency', },
  { id: 91, label: 'Structural Fire', },
  { id: 92, label: 'Traffic signal', },
  { id: 93, label: 'Travel advisory', },
  { id: 94, label: 'Tree on road', },
  { id: 95, label: 'Unplanned Protest or Special Event', },
  { id: 96, label: 'Unplanned service interruption (Ferries)', },
  { id: 97, label: 'Vehicle fire', },
  { id: 98, label: 'Vehicle incident', },
  { id: 99, label: 'Vehicle recovery', },
  { id: 100, label: 'Vehicle stall', },
  { id: 101, label: 'Washout', },
  { id: 102, label: 'Washrooms Closed', },
  { id: 103, label: 'Water pooling', },
  { id: 104, label: 'Weather advisory', },
  { id: 105, label: 'Wildfire', },
  { id: 106, label: 'Wildlife advisory', },
  { id: 107, label: 'Winter Operations', }
];
