export const TrafficImpacts = [
  { id: 0, label: '', closed: false },
  { id: 1, label: 'All lanes blocked', closed: true },
  { id: 2, label: 'Assessment in progress', closed: false },
  { id: 3, label: 'Bridge closed', closed: true },
  { id: 4, label: 'Centre lane blocked', closed: false },
  { id: 5, label: 'Centre lane closed', closed: false },
  { id: 6, label: 'Centre lane closed in both directions', closed: false },
  { id: 7, label: 'Closed', closed: true },
  { id: 9, label: 'Closed for repairs', closed: true },
  { id: 10, label: 'Closed for the season', closed: true },
  { id: 11, label: 'Closed intermittently', closed: false },
  { id: 12, label: 'Closed to all traffic except emergency vehicles', closed: true },
  { id: 13, label: 'Detour in effect', closed: false },
  { id: 14, label: 'Eastbound lane closure', closed: false },
  { id: 15, label: 'Emergency vehicles on scene', closed: false },
  { id: 16, label: 'Entrance ramp closed', closed: true },
  { id: 17, label: 'Essential travel only', closed: false },
  { id: 18, label: 'Estimated time of opening not available', closed: true },
  { id: 19, label: 'Exit ramp closed', closed: false },
  { id: 20, label: 'Expect delays', closed: false },
  { id: 21, label: 'Expect delays due to congestion', closed: false },
  { id: 22, label: 'Expect major delays', closed: false },
  { id: 23, label: 'Expect major delays due to congestion', closed: false },
  { id: 24, label: 'Expect minor delays', closed: false },
  { id: 25, label: 'Heavy congestion', closed: false },
  { id: 26, label: 'HOV lane closed', closed: false },
  { id: 27, label: 'Lane blocked', closed: false },
  { id: 28, label: 'Lane closures in both directions', closed: false },
  { id: 29, label: 'Left lane blocked', closed: false },
  { id: 30, label: 'Left lane closed', closed: false },
  { id: 31, label: 'Left lane closed in both directions', closed: false },
  { id: 32, label: 'Left shoulder closed', closed: false },
  { id: 33, label: 'Left turn lane closed', closed: false },
  { id: 34, label: 'Minor congestion', closed: false },
  { id: 35, label: 'No detour available', closed: false },
  { id: 36, label: 'Northbound lane closure', closed: false },
  { id: 37, label: 'On-ramp Shift', closed: false },
  { id: 38, label: 'Open to traffic', closed: false },
  { id: 39, label: 'Paving operations', closed: false },
  { id: 40, label: 'Plowing and sanding', closed: false },
  { id: 41, label: 'Possible delays', closed: false },
  { id: 42, label: 'Possible delays due to heavy traffic volumes', closed: false },
  { id: 43, label: 'Ramp blocked', closed: false },
  { id: 44, label: 'Reduced to one lane', closed: false },
  { id: 45, label: 'Reduced to two lanes', closed: false },
  { id: 46, label: 'Right lane blocked', closed: false },
  { id: 47, label: 'Right lane closed', closed: false },
  { id: 48, label: 'Right lane closed in both directions', closed: false },
  { id: 49, label: 'Right lane of exit ramp closed', closed: false },
  { id: 50, label: 'Right turn lane closed', closed: false },
  { id: 51, label: 'Road closure', closed: true },
  { id: 52, label: 'Road open', closed: false },
  { id: 53, label: 'Sanded', closed: false },
  { id: 54, label: 'Shoulder closed', closed: false },
  { id: 55, label: 'Single lane alternating traffic', closed: false },
  { id: 56, label: 'Slow down and drive to winter conditions', closed: false },
  { id: 57, label: 'Southbound lane closure', closed: false },
  { id: 58, label: 'Traffic signal out', closed: false },
  { id: 59, label: 'Truck lane available for all vehicles', closed: false },
  { id: 60, label: 'Truck restriction', closed: false },
  { id: 61, label: 'Two centre lanes blocked', closed: false },
  { id: 62, label: 'Two centre lanes closed', closed: false },
  { id: 63, label: 'Two left lanes blocked', closed: false },
  { id: 64, label: 'Two left lanes of exit ramp blocked', closed: false },
  { id: 65, label: 'Two right lanes blocked', closed: false },
  { id: 66, label: 'Two right lanes of exit ramp blocked', closed: false },
  { id: 67, label: 'Watch for traffic control', closed: false },
  { id: 68, label: 'Westbound lane closure', closed: false },
];

export const RestrictionsList = [
  { id: 0, label: '', },
  { id: 1, label: 'Axle Count', placeholder: '# of Axles (2-12)' },
  { id: 2, label: 'Height', placeholder: 'Meters (max 6)' },
  { id: 3, label: 'Length', placeholder: 'Meters (max 40)' },
  { id: 4, label: 'Speed Limit', placeholder: 'Kilometers per hour (60-120)' },
  { id: 7, label: 'Weight axle', placeholder: 'Kilograms (10-64,000)' },
  { id: 8, label: 'Weight vehicle', placeholder: 'Kilograms (10-64,000)' },
  { id: 9, label: 'Width', placeholder: 'Meters (max 10)' },
];

export const RoadConditions = [
  { id: 0, label: '', },
  { id: 1, label: 'Black ice', },
  { id: 2, label: 'Compact ice', },
  { id: 3, label: 'Slippery sections', },
  { id: 4, label: 'Slushy sections', },
  { id: 5, label: 'Compact snow', },
  { id: 6, label: 'High flood warning', },
  { id: 7, label: 'Sanded', },
  { id: 8, label: 'Plowing and sanding', },
  { id: 9, label: 'Muddy Sections', },
  { id: 10, label: 'Fog patches', },
  { id: 11, label: 'Heavy slush', },
  { id: 12, label: 'Water pooling', },
  { id: 13, label: 'Slushy Sections', },
  { id: 14, label: 'Slushy with slippery sections', },
  { id: 15, label: 'Rain on compact snow', },
  { id: 16, label: 'Debris on road', },
  { id: 17, label: 'Bridge Closed (Road Condition)', },
];

export const IncidentsList = [
  { id: 0, label: '', },
  { id: 1, label: '1 sailing wait (Ferries)', },
  { id: 2, label: '2 sailing wait (Ferries)', },
  { id: 3, label: '3 sailing wait (Ferries)', },
  { id: 4, label: '4 sailing wait (Ferries)', },
  { id: 5, label: '5-6 sailing wait (Ferries)', },
  { id: 6, label: '> 6 sailing wait (Ferries)', },
  { id: 7, label: 'Adverse weather (Ferries)', },
  { id: 8, label: 'Adverse weather (Ferries)', },
  { id: 9, label: 'Avalanche', },
  { id: 10, label: 'Avalanche control activities', },
  { id: 11, label: 'Avalanche Deposit Removal', },
  { id: 12, label: 'Avalanche Hazard', },
  { id: 13, label: 'Behind schedule >90 (Ferries)', },
  { id: 14, label: 'Behind schedule 20 (Ferries)', },
  { id: 15, label: 'Behind schedule 30 (Ferries)', },
  { id: 16, label: 'Behind schedule 40 (Ferries)', },
  { id: 17, label: 'Behind schedule 50 (Ferries)', },
  { id: 18, label: 'Behind schedule 60-90 (Ferries)', },
  { id: 19, label: 'Bridge closed', },
  { id: 20, label: 'Bridge damage', },
  { id: 21, label: 'Bridge wash out', },
  { id: 22, label: 'Cleared', },
  { id: 23, label: 'Collision', },
  { id: 24, label: 'Collision (closed)', },
  { id: 25, label: 'Crewing issues (Ferries)', },
  { id: 26, label: 'Crewing issues (Ferries)', },
  { id: 27, label: 'Debris in water (Ferries)', },
  { id: 28, label: 'Debris on road', },
  { id: 29, label: 'Delayed departure (Ferries)', },
  { id: 30, label: 'Delays >90 (Ferries)', },
  { id: 31, label: 'Expect delay >90 (Ferries)', },
  { id: 32, label: 'Expect delay 20 (Ferries)', },
  { id: 33, label: 'Expect delay 30 (Ferries)', },
  { id: 34, label: 'Expect delay 40 (Ferries)', },
  { id: 35, label: 'Expect delay 50 (Ferries)', },
  { id: 36, label: 'Expect delay 60-90 (Ferries)', },
  { id: 37, label: 'Falling ice', },
  { id: 38, label: 'Falling rock', },
  { id: 39, label: 'Ferry operating 24hrs (Ferries)', },
  { id: 40, label: 'Fire Travel Advisory - Special Incident', },
  { id: 41, label: 'Flooded', },
  { id: 42, label: 'Forest Fire', },
  { id: 43, label: 'Freshet (Ferries)', },
  { id: 44, label: 'Freshet (Ferries)', },
  { id: 45, label: 'Grass Fire', },
  { id: 46, label: 'Hazardous materials', },
  { id: 47, label: 'High avalanche hazard', },
  { id: 48, label: 'High river current (Ferries)', },
  { id: 49, label: 'High traffic volume (Ferries)', },
  { id: 50, label: 'Highway closure (Ferries)', },
  { id: 51, label: 'Hydro lines down', },
  { id: 52, label: 'Industrial Traffic', },
  { id: 53, label: 'Landslide', },
  { id: 54, label: 'Limited visibility', },
  { id: 55, label: 'Livestock warning', },
  { id: 56, label: 'Marine traffic (Ferries)', },
  { id: 57, label: 'Material spill', },
  { id: 58, label: 'Mechanical issue (Ferries)', },
  { id: 59, label: 'Mechanical issue (Ferries)', },
  { id: 60, label: 'Medical emergency (Ferries)', },
  { id: 61, label: 'Medical emergency (Ferries)', },
  { id: 62, label: 'Mudslide', },
  { id: 63, label: 'Multi-vehicle Incident', },
  { id: 64, label: 'Obstruction on roadway', },
  { id: 65, label: 'Operational delay (Ferries)', },
  { id: 66, label: 'Police incident', },
  { id: 67, label: 'Possible ferry delays (Ferries)', },
  { id: 68, label: 'Railway crossing incident', },
  { id: 69, label: 'Replacement vessel (Ferries)', },
  { id: 70, label: 'Required maintenance (Ferries)', },
  { id: 71, label: 'Required maintenance (Ferries)', },
  { id: 72, label: 'Rest area closed', },
  { id: 73, label: 'Rock slide', },
  { id: 74, label: 'Rocks on Road', },
  { id: 75, label: 'Safety drills (Ferries)', },
  { id: 76, label: 'Safety drills (Ferries)', },
  { id: 77, label: 'Safety inspection (Ferries)', },
  { id: 78, label: 'Safety inspection (Ferries)', },
  { id: 79, label: 'Sailing wait at East Side (Ferries)', },
  { id: 80, label: 'Sailing wait at East Terminal (Ferries)', },
  { id: 81, label: 'Sailing wait at North Bank (Ferries)', },
  { id: 82, label: 'Sailing wait at North Terminal (Ferries)', },
  { id: 83, label: 'Sailing wait at South Bank (Ferries)', },
  { id: 84, label: 'Sailing wait at South Terminal (Ferries)', },
  { id: 85, label: 'Sailing wait at West Side (Ferries)', },
  { id: 86, label: 'Sailing wait at West Terminal (Ferries)', },
  { id: 87, label: 'Seasonal shutdown (Ferries)', },
  { id: 88, label: 'Seasonal shutdown (Ferries)', },
  { id: 89, label: 'Seasonal Shutdown(Ferries)', },
  { id: 90, label: 'State of Emergency', },
  { id: 91, label: 'Structural Fire', },
  { id: 92, label: 'Traffic signal', },
  { id: 93, label: 'Travel advisory', },
  { id: 94, label: 'Tree on road', },
  { id: 95, label: 'Unplanned Protest or Special Event', },
  { id: 96, label: 'Unplanned service interruption (Ferries)', },
  { id: 97, label: 'Vehicle fire', },
  { id: 98, label: 'Vehicle incident', },
  { id: 99, label: 'Vehicle recovery', },
  { id: 100, label: 'Vehicle stall', },
  { id: 101, label: 'Washout', },
  { id: 102, label: 'Washrooms Closed', },
  { id: 103, label: 'Water pooling', },
  { id: 104, label: 'Weather advisory', },
  { id: 105, label: 'Wildfire', },
  { id: 106, label: 'Wildlife advisory', },
  { id: 107, label: 'Winter Operations', }
];

export const COLUMNS = ['RIDE Event type', 'RIDE Category', 'RIDE Situation', 'id', 'DIT type 1', 'category_id',' Open511 Type', 'subtype_id', 'Open511 Sub-type'];

export const PHRASES = [
  ['Chain-up', '-', 'Commercial chain-up in effect', 2, 'PHRASE', 2,' CHAIN_UP', 1, 'HAZARD'],
  ['Incident', 'Avalanche', 'Avalanche', 84, 'PHRASE', 1,' INCIDENT', 6, 'AVALANCHE_HAZARD'],
  ['Incident', 'Avalanche', 'Avalanche control activities', 279, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Avalanche', 'Avalanche deposit removal', 283, 'PHRASE', 1,' INCIDENT', 6, 'AVALANCHE_HAZARD'],
  ['Incident', 'Avalanche', 'High avalanche hazard', 86, 'PHRASE', 1,' INCIDENT', 6, 'AVALANCHE_HAZARD'],
  ['Incident', 'Ferry', '> 6 sailing wait', 257, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Ferry', '1 sailing wait', 252, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Ferry', '2 sailing wait', 253, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Ferry', '3 sailing wait', 254, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Ferry', '4 sailing wait', 255, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Ferry', '5-6 sailing wait', 256, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Ferry', 'Adverse weather', 233, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Ferry', 'Behind schedule >90 minutes', 264, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Ferry', 'Behind schedule 20 minutes', 258, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Ferry', 'Behind schedule 30 minutes', 259, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Ferry', 'Behind schedule 40 minutes', 261, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Ferry', 'Behind schedule 50 minutes', 262, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Ferry', 'Behind schedule 60-90 minutes', 263, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Ferry', 'Crewing issues', 234, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Ferry', 'Debris in water', 165, 'ADVICE', 1,' INCIDENT', 2, 'NULL'],
  ['Incident', 'Ferry', 'Delayed departure', 74, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Ferry', 'Expect delay >90 minutes', 281, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Ferry', 'Expect delay of 20 minutes', 265, 'ADVICE', 1,' INCIDENT', 2, 'NULL'],
  ['Incident', 'Ferry', 'Expect delay of 30 minutes', 266, 'ADVICE', 1,' INCIDENT', 2, 'NULL'],
  ['Incident', 'Ferry', 'Expect delay of 40 minutes', 267, 'ADVICE', 1,' INCIDENT', 2, 'NULL'],
  ['Incident', 'Ferry', 'Expect delay of 50 minutes', 268, 'ADVICE', 1,' INCIDENT', 2, 'NULL'],
  ['Incident', 'Ferry', 'Expect delay of 60-90 minutes', 269, 'ADVICE', 1,' INCIDENT', 2, 'NULL'],
  ['Incident', 'Ferry', 'Ferry operating 24 hours a day', 271, 'ADVICE', 1,' INCIDENT', 2, 'NULL'],
  ['Incident', 'Ferry', 'Freshet (flooding)', 235, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Ferry', 'High river current', 164, 'ADVICE', 1,' INCIDENT', 2, 'NULL'],
  ['Incident', 'Ferry', 'High traffic volume', 153, 'ADVICE', 1,' INCIDENT', 2, 'NULL'],
  ['Incident', 'Ferry', 'Marine traffic', 168, 'ADVICE', 1,' INCIDENT', 2, 'NULL'],
  ['Incident', 'Ferry', 'Mechanical issue', 289, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Ferry', 'Medical emergency', 240, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Ferry', 'Possible ferry delays', 224, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Ferry', 'Replacement vessel', 158, 'ADVICE', 1,' INCIDENT', 2, 'NULL'],
  ['Incident', 'Ferry', 'Required maintenance', 156, 'ADVICE', 1,' INCIDENT', 2, 'NULL'],
  ['Incident', 'Ferry', 'Safety drills', 161, 'ADVICE', 1,' INCIDENT', 2, 'NULL'],
  ['Incident', 'Ferry', 'Safety inspection', 160, 'ADVICE', 1,' INCIDENT', 2, 'NULL'],
  ['Incident', 'Ferry', 'Sailing wait at East Side', 151, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Ferry', 'Sailing wait at East Terminal', 82, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Ferry', 'Sailing wait at North Bank', 149, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Ferry', 'Sailing wait at North Terminal', 147, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Ferry', 'Sailing wait at South Bank', 150, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Ferry', 'Sailing wait at South Terminal', 148, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Ferry', 'Sailing wait at West Side', 152, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Ferry', 'Sailing wait at West Terminal', 146, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Ferry', 'Unplanned service interruption', 73, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Incident', 'Hazard', 'Bridge closed', 90, 'PHRASE', 1,' INCIDENT', 1, 'HAZARD'],
  ['Incident', 'Hazard', 'Bridge damage', 91, 'PHRASE', 1,' INCIDENT', 1, 'HAZARD'],
  ['Incident', 'Hazard', 'Bridge wash out', 92, 'PHRASE', 1,' INCIDENT', 1, 'HAZARD'],
  ['Incident', 'Hazard', 'Debris on road', 104, 'PHRASE', 1,' INCIDENT', 15, 'OBSTRUCTION'],
  ['Incident', 'Hazard', 'Falling ice', 76, 'PHRASE', 1,' INCIDENT', 1, 'HAZARD'],
  ['Incident', 'Hazard', 'Falling rock', 77, 'PHRASE', 1,' INCIDENT', 1, 'HAZARD'],
  ['Incident', 'Hazard', 'Flooding', 78, 'PHRASE', 1,' INCIDENT', 1, 'HAZARD'],
  ['Incident', 'Hazard', 'Forest fire', 87, 'PHRASE', 1,' INCIDENT', 13, 'FIRE'],
  ['Incident', 'Hazard', 'Grass fire', 188, 'PHRASE', 1,' INCIDENT', 13, 'FIRE'],
  ['Incident', 'Hazard', 'Hazardous materials spill', 79, 'PHRASE', 1,' INCIDENT', 1, 'HAZARD'],
  ['Incident', 'Hazard', 'Hydro lines down', 80, 'PHRASE', 1,' INCIDENT', 1, 'HAZARD'],
  ['Incident', 'Hazard', 'Industrial traffic', 285, 'PHRASE', 1,' INCIDENT', 1, 'HAZARD'],
  ['Incident', 'Hazard', 'Landslide', 296, 'PHRASE', 1,' INCIDENT', 1, 'HAZARD'],
  ['Incident', 'Hazard', 'Limited visibility', 106, 'PHRASE', 1,' INCIDENT', 16, 'POOR_VISIBILITY'],
  ['Incident', 'Hazard', 'Livestock on road', 305, 'PHRASE', 1,' INCIDENT', 1, 'HAZARD'],
  ['Incident', 'Hazard', 'Material spill', 108, 'PHRASE', 1,' INCIDENT', 18, 'SPILL'],
  ['Incident', 'Hazard', 'Mudslide', 103, 'PHRASE', 1,' INCIDENT', 14, 'MUD'],
  ['Incident', 'Hazard', 'Multi-vehicle Incident', 203, 'PHRASE', 1,' INCIDENT', 1, 'HAZARD'],
  ['Incident', 'Hazard', 'Obstruction on roadway', 105, 'PHRASE', 1,' INCIDENT', 15, 'OBSTRUCTION'],
  ['Incident', 'Hazard', 'Police incident', 81, 'PHRASE', 1,' INCIDENT', 1, 'HAZARD'],
  ['Incident', 'Hazard', 'Railway crossing incident', 93, 'PHRASE', 1,' INCIDENT', 1, 'HAZARD'],
  ['Incident', 'Hazard', 'Rock slide', 95, 'PHRASE', 1,' INCIDENT', 1, 'HAZARD'],
  ['Incident', 'Hazard', 'Rocks on road', 192, 'PHRASE', 1,' INCIDENT', 1, 'HAZARD'],
  ['Incident', 'Hazard', 'State of emergency', 218, 'PHRASE', 1,' INCIDENT', 1, 'HAZARD'],
  ['Incident', 'Hazard', 'Structural fire', 88, 'PHRASE', 1,' INCIDENT', 13, 'FIRE'],
  ['Incident', 'Hazard', 'Traffic signal out', 107, 'PHRASE', 1,' INCIDENT', 17, 'SIGNAL_LIGHT_FAILURE'],
  ['Incident', 'Hazard', 'Tree on road', 96, 'PHRASE', 1,' INCIDENT', 1, 'HAZARD'],
  ['Incident', 'Hazard', 'Vehicle collision', 72, 'PHRASE', 1,' INCIDENT', 1, 'HAZARD'],
  ['Incident', 'Hazard', 'Vehicle fire', 89, 'PHRASE', 1,' INCIDENT', 13, 'FIRE'],
  ['Incident', 'Hazard', 'Vehicle incident', 144, 'PHRASE', 1,' INCIDENT', 1, 'HAZARD'],
  ['Incident', 'Hazard', 'Vehicle recovery', 97, 'PHRASE', 1,' INCIDENT', 1, 'HAZARD'],
  ['Incident', 'Hazard', 'Vehicle stall', 98, 'PHRASE', 1,' INCIDENT', 1, 'HAZARD'],
  ['Incident', 'Hazard', 'Washout', 99, 'PHRASE', 1,' INCIDENT', 1, 'HAZARD'],
  ['Incident', 'Hazard', 'Washrooms closed', 295, 'PHRASE', 1,' INCIDENT', 8, 'ROAD_MAINTENANCE'],
  ['Incident', 'Hazard', 'Water pooling', 100, 'PHRASE', 1,' INCIDENT', 1, 'HAZARD'],
  ['Incident', 'Hazard', 'Wildfire', 298, 'PHRASE', 1,' INCIDENT', 13, 'FIRE'],
  ['Incident', 'Hazard', 'Wildlife advisory', 102, 'PHRASE', 1,' INCIDENT', 1, 'HAZARD'],
  ['Incident', 'Hazard', 'Winter operations', 300, 'PHRASE', 1,' INCIDENT', null, 'ROAD_MAINTENANCE'],
  ['Incident', 'Special event', 'Unplanned protest or special event', 287, 'PHRASE', 1,' INCIDENT', 1, 'HAZARD'],
  ['Planned event', 'Avalanche', 'Avalanche control activities', 13, 'PHRASE', 4,' CONSTRUCTION', 8, 'ROAD_MAINTENANCE'],
  ['Planned event', 'Avalanche', 'Avalanche deposit removal', 292, 'PHRASE', 4,' CONSTRUCTION', 6, 'AVALANCHE_HAZARD'],
  ['Planned event', 'Construction', 'Blasting', 10, 'PHRASE', 4,' CONSTRUCTION', 7, 'ROAD_CONSTRUCTION'],
  ['Planned event', 'Construction', 'Bridge construction', 11, 'PHRASE', 4,' CONSTRUCTION', 7, 'ROAD_CONSTRUCTION'],
  ['Planned event', 'Construction', 'Patching', 282, 'PHRASE', 4,' CONSTRUCTION', 7, 'ROAD_CONSTRUCTION'],
  ['Planned event', 'Construction', 'Road construction', 12, 'PHRASE', 4,' CONSTRUCTION', 7, 'ROAD_CONSTRUCTION'],
  ['Planned event', 'Construction', 'Rock slope stabilization', 226, 'PHRASE', 4,' CONSTRUCTION', 7, 'ROAD_CONSTRUCTION'],
  ['Planned event', 'Ferry', 'Additional service', 118, 'PHRASE', 4,' CONSTRUCTION', 1, 'HAZARD'],
  ['Planned event', 'Ferry', 'Planned service interruption', 4, 'PHRASE', 4,' CONSTRUCTION', 3, 'ALMOST_IMPASSABLE'],
  ['Planned event', 'Ferry', 'Possible service interruptions', 9, 'PHRASE', 4,' CONSTRUCTION', 3, 'ALMOST_IMPASSABLE'],
  ['Planned event', 'Ferry', 'Required maintenance', 239, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Planned event', 'Ferry', 'Safety drills', 238, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Planned event', 'Ferry', 'Safety inspection', 304, 'PHRASE', 4,' CONSTRUCTION', 3, 'ALMOST_IMPASSABLE'],
  ['Planned event', 'Ferry', 'Seasonal shutdown', 236, 'PHRASE', 1,' INCIDENT', 3, 'ALMOST_IMPASSABLE'],
  ['Planned event', 'Maintenance', 'Bridge maintenance', 15, 'PHRASE', 4,' CONSTRUCTION', 8, 'ROAD_MAINTENANCE'],
  ['Planned event', 'Maintenance', 'Construction work', 19, 'PHRASE', 4,' CONSTRUCTION', 8, 'ROAD_MAINTENANCE'],
  ['Planned event', 'Maintenance', 'Crack sealing', 284, 'PHRASE', 4,' CONSTRUCTION', 8, 'ROAD_MAINTENANCE'],
  ['Planned event', 'Maintenance', 'Ditch maintenance', 205, 'PHRASE', 4,' CONSTRUCTION', 8, 'ROAD_MAINTENANCE'],
  ['Planned event', 'Maintenance', 'Electrical maintenance', 245, 'PHRASE', 4,' CONSTRUCTION', 8, 'ROAD_MAINTENANCE'],
  ['Planned event', 'Maintenance', 'Garbage pick up', 21, 'PHRASE', 4,' CONSTRUCTION', 8, 'ROAD_MAINTENANCE'],
  ['Planned event', 'Maintenance', 'Geotechnical investigation', 280, 'PHRASE', 4,' CONSTRUCTION', 8, 'ROAD_MAINTENANCE'],
  ['Planned event', 'Maintenance', 'Line painting', 25, 'PHRASE', 4,' CONSTRUCTION', 8, 'ROAD_MAINTENANCE'],
  ['Planned event', 'Maintenance', 'Mowing', 191, 'PHRASE', 4,' CONSTRUCTION', 7, 'ROAD_CONSTRUCTION'],
  ['Planned event', 'Maintenance', 'New traffic signal', 28, 'PHRASE', 4,' CONSTRUCTION', 8, 'ROAD_MAINTENANCE'],
  ['Planned event', 'Maintenance', 'Night work', 68, 'PHRASE', 4,' CONSTRUCTION', 8, 'ROAD_MAINTENANCE'],
  ['Planned event', 'Maintenance', 'Paving operations', 69, 'PHRASE', 4,' CONSTRUCTION', 8, 'ROAD_MAINTENANCE'],
  ['Planned event', 'Maintenance', 'Pothole repair', 70, 'PHRASE', 4,' CONSTRUCTION', 8, 'ROAD_MAINTENANCE'],
  ['Planned event', 'Maintenance', 'Rest area closed', 94, 'PHRASE', 1,' INCIDENT', 1, 'HAZARD'],
  ['Planned event', 'Maintenance', 'Road maintenance', 71, 'PHRASE', 4,' CONSTRUCTION', 8, 'ROAD_MAINTENANCE'],
  ['Planned event', 'Maintenance', 'Road seal coating', 112, 'PHRASE', 4,' CONSTRUCTION', 8, 'ROAD_MAINTENANCE'],
  ['Planned event', 'Maintenance', 'Road sweeping', 109, 'PHRASE', 4,' CONSTRUCTION', 8, 'ROAD_MAINTENANCE'],
  ['Planned event', 'Maintenance', 'Roadside brushing', 110, 'PHRASE', 4,' CONSTRUCTION', 8, 'ROAD_MAINTENANCE'],
  ['Planned event', 'Maintenance', 'Rock scaling', 111, 'PHRASE', 4,' CONSTRUCTION', 8, 'ROAD_MAINTENANCE'],
  ['Planned event', 'Maintenance', 'Shoulder maintenance', 251, 'PHRASE', 4,' CONSTRUCTION', 8, 'ROAD_MAINTENANCE'],
  ['Planned event', 'Maintenance', 'Snow deposit removal', 113, 'PHRASE', 4,' CONSTRUCTION', 8, 'ROAD_MAINTENANCE'],
  ['Planned event', 'Maintenance', 'Traffic signal out', 117, 'PHRASE', 4,' CONSTRUCTION', 17, 'SIGNAL_LIGHT_FAILURE'],
  ['Planned event', 'Maintenance', 'Tree pruning', 114, 'PHRASE', 4,' CONSTRUCTION', 8, 'ROAD_MAINTENANCE'],
  ['Planned event', 'Maintenance', 'Utility work', 115, 'PHRASE', 4,' CONSTRUCTION', 8, 'ROAD_MAINTENANCE'],
  ['Planned event', 'Maintenance', 'Vehicle recovery', 116, 'PHRASE', 4,' CONSTRUCTION', 8, 'ROAD_MAINTENANCE'],
  ['Planned event', 'Special event', 'Special event', 7, 'PHRASE', 7,' SPECIAL_EVENT', 5, 'PLANNED_EVENT'],
  ['Road condition', '-', 'Road condition', 2, 'PHRASE', 2,' CHAIN_UP', 1, 'HAZARD'],
];

export const DETAILS_FORMS = ['Chain-up', 'Incident', 'Planned event'];
export const DELAYS_FORMS = ['Chain-up', 'Incident', 'Planned event'];
export const IMPACTS_FORMS = ['Chain-up', 'Incident', 'Planned event'];
export const RESTRICTIONS_FORMS = ['Chain-up', 'Incident', 'Planned event'];
export const CONDITIONS_FORMS = ['Road condition'];

export const FORMS = []; window.FORMS = FORMS;
export const FORM_CATEGORIES = {}; window.FORM_CATEGORIES = FORM_CATEGORIES;
export const FORM_PHRASES = {}; window.FORM_PHRASES = FORM_PHRASES;
export const FORM_PHRASE_CATEGORY = {}; window.FORM_PHRASE_CATEGORY = FORM_PHRASE_CATEGORY;
export const PHRASES_LOOKUP = {}; window.PHRASES_LOOKUP = PHRASES_LOOKUP;
export const FORM_CATEGORY_PHRASE = PHRASES.reduce((acc, row, ii) => {
  const form = row[0];
  const category = row[1];
  const phrase = row[2];
  const id = row[3];

  if (!acc[form]) {
    acc[form] = {};
    FORM_CATEGORIES[form] = []
    FORM_PHRASES[form] = []
    FORM_PHRASE_CATEGORY[form] = {};
    FORMS.push(form);
  }
  if (!acc[form][category]) {
    acc[form][category] = [];
    FORM_CATEGORIES[form].push(category);
  }
  acc[form][category].push({ id, phrase });
  FORM_PHRASES[form].push({ id, phrase });
  FORM_PHRASE_CATEGORY[form][id] = category;
  PHRASES_LOOKUP[id] = phrase;
  return acc;
}, {}); window.FORM_CATEGORY_PHRASE = FORM_CATEGORY_PHRASE

