impacts = [
  { 'id': 1, 'label': 'All lanes blocked', 'closed': True },
  { 'id': 2, 'label': 'Assessment in progress', 'closed': False },
  { 'id': 3, 'label': 'Bridge closed', 'closed': True },
  { 'id': 4, 'label': 'Centre lane blocked', 'closed': False },
  { 'id': 5, 'label': 'Centre lane closed', 'closed': False },
  { 'id': 6, 'label': 'Centre lane closed in both directions', 'closed': False },
  { 'id': 7, 'label': 'Closed', 'closed': True },
  { 'id': 9, 'label': 'Closed for repairs', 'closed': True },
  { 'id': 10, 'label': 'Closed for the season', 'closed': True },
  { 'id': 11, 'label': 'Closed intermittently', 'closed': False },
  { 'id': 12, 'label': 'Closed to all traffic except emergency vehicles', 'closed': True },
  { 'id': 13, 'label': 'Detour in effect', 'closed': False },
  { 'id': 14, 'label': 'Eastbound lane closure', 'closed': False },
  { 'id': 15, 'label': 'Emergency vehicles on scene', 'closed': False },
  { 'id': 16, 'label': 'Entrance ramp closed', 'closed': True },
  { 'id': 17, 'label': 'Essential travel only', 'closed': False },
  { 'id': 18, 'label': 'Estimated time of opening not available', 'closed': True },
  { 'id': 19, 'label': 'Exit ramp closed', 'closed': False },
  { 'id': 20, 'label': 'Expect delays', 'closed': False },
  { 'id': 21, 'label': 'Expect delays due to congestion', 'closed': False },
  { 'id': 22, 'label': 'Expect major delays', 'closed': False },
  { 'id': 23, 'label': 'Expect major delays due to congestion', 'closed': False },
  { 'id': 24, 'label': 'Expect minor delays', 'closed': False },
  { 'id': 25, 'label': 'Heavy congestion', 'closed': False },
  { 'id': 26, 'label': 'HOV lane closed', 'closed': False },
  { 'id': 27, 'label': 'Lane blocked', 'closed': False },
  { 'id': 28, 'label': 'Lane closures in both directions', 'closed': False },
  { 'id': 29, 'label': 'Left lane blocked', 'closed': False },
  { 'id': 30, 'label': 'Left lane closed', 'closed': False },
  { 'id': 31, 'label': 'Left lane closed in both directions', 'closed': False },
  { 'id': 32, 'label': 'Left shoulder closed', 'closed': False },
  { 'id': 33, 'label': 'Left turn lane closed', 'closed': False },
  { 'id': 34, 'label': 'Minor congestion', 'closed': False },
  { 'id': 35, 'label': 'No detour available', 'closed': False },
  { 'id': 36, 'label': 'Northbound lane closure', 'closed': False },
  { 'id': 37, 'label': 'On-ramp Shift', 'closed': False },
  { 'id': 38, 'label': 'Open to traffic', 'closed': False },
  { 'id': 39, 'label': 'Paving operations', 'closed': False },
  { 'id': 40, 'label': 'Plowing and sanding', 'closed': False },
  { 'id': 41, 'label': 'Possible delays', 'closed': False },
  { 'id': 42, 'label': 'Possible delays due to heavy traffic volumes', 'closed': False },
  { 'id': 43, 'label': 'Ramp blocked', 'closed': False },
  { 'id': 44, 'label': 'Reduced to one lane', 'closed': False },
  { 'id': 45, 'label': 'Reduced to two lanes', 'closed': False },
  { 'id': 46, 'label': 'Right lane blocked', 'closed': False },
  { 'id': 47, 'label': 'Right lane closed', 'closed': False },
  { 'id': 48, 'label': 'Right lane closed in both directions', 'closed': False },
  { 'id': 49, 'label': 'Right lane of exit ramp closed', 'closed': False },
  { 'id': 50, 'label': 'Right turn lane closed', 'closed': False },
  { 'id': 51, 'label': 'Road closure', 'closed': True },
  { 'id': 52, 'label': 'Road open', 'closed': False },
  { 'id': 53, 'label': 'Sanded', 'closed': False },
  { 'id': 54, 'label': 'Shoulder closed', 'closed': False },
  { 'id': 55, 'label': 'Single lane alternating traffic', 'closed': False },
  { 'id': 56, 'label': 'Slow down and drive to winter conditions', 'closed': False },
  { 'id': 57, 'label': 'Southbound lane closure', 'closed': False },
  { 'id': 58, 'label': 'Traffic signal out', 'closed': False },
  { 'id': 59, 'label': 'Truck lane available for all vehicles', 'closed': False },
  { 'id': 60, 'label': 'Truck restriction', 'closed': False },
  { 'id': 61, 'label': 'Two centre lanes blocked', 'closed': False },
  { 'id': 62, 'label': 'Two centre lanes closed', 'closed': False },
  { 'id': 63, 'label': 'Two left lanes blocked', 'closed': False },
  { 'id': 64, 'label': 'Two left lanes of exit ramp blocked', 'closed': False },
  { 'id': 65, 'label': 'Two right lanes blocked', 'closed': False },
  { 'id': 66, 'label': 'Two right lanes of exit ramp blocked', 'closed': False },
  { 'id': 67, 'label': 'Watch for traffic control', 'closed': False },
  { 'id': 68, 'label': 'Westbound lane closure', 'closed': False },
]

from pprint import pprint
from django.core.management.base import BaseCommand, CommandError

from apps.events.models import TrafficImpact


class Command(BaseCommand):

    def handle(self, *args, **options):
        for impact in impacts:
            TrafficImpact.objects.update_or_create(**impact, order=impact['id'])
