# Generated by Django 5.2 on 2026-01-27 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='route',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Segment',
        ),
    ]
