# Generated by Django 5.2 on 2026-01-27 23:29

from django.core.management import call_command
from django.db import migrations

from apps.events.models import TrafficImpact, Condition, Event
from apps.segments.models import Segment


def load_references(apps, schema_editor):
    call_command('load_references')

def reverse_references(apps, schema_editor):
    TrafficImpact.objects.all().delete()
    Condition.objects.all().delete()

def load_fixture(apps, schema_editor):
    call_command('purge_segments', app_label='segments')
    call_command('loaddata', 'segments.json', app_label='segments')
    call_command('update_segments', app_label='segments')

def reverse_fixture(apps, schema_editor):
    Event.objects.all().delete()
    Segment.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0003_initial'),
    ]

    operations = [
        migrations.RunPython(load_references, reverse_references),
        migrations.RunPython(load_fixture, reverse_fixture),
    ]