# Generated by Django 5.2 on 2026-01-27 23:29

from django.core.management import call_command
from django.db import migrations

def load_fixture(apps, schema_editor):
    Route = apps.get_model('segments', 'Route')
    Segment = apps.get_model('segments', 'Segment')

    Route.objects.all().delete()
    Segment.objects.all().delete()
    call_command('loaddata', 'segments.json', app_label='segments')
    Segment.objects.all().update(latest=True)

def reverse_fixture(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    Segment = apps.get_model('segments', 'Segment')

    Event.objects.all().delete()
    Segment.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('segments', '0003_initial'),
        ('events', '0010_condition_alter_event_managers_event_segment'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_fixture),
    ]