# Generated by Django 5.2 on 2026-02-07 00:16

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_organization_contact_id_and_more'),
        ('segments', '0004_auto_20260127_2329'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segment',
            options={},
        ),
        migrations.CreateModel(
            name='ChainUp',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id', models.CharField(blank=True, max_length=20, null=True)),
                ('version', models.IntegerField(default=0)),
                ('latest', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=90)),
                ('description', models.CharField(max_length=255)),
                ('sorting_order', models.PositiveIntegerField()),
                ('primary_mp', models.FloatField()),
                ('primary_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('secondary_mp', models.FloatField()),
                ('secondary_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.servicearea')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segments.route')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
