# Generated by Django 5.2 on 2026-02-18 18:41
from django.core.management import call_command
from django.db import migrations, models

from apps.segments.models import ChainUp


class Migration(migrations.Migration):
    def load_fixture(apps, schema_editor):
        call_command('loaddata', 'chainups.json', app_label='segments')

    def reverse_fixture(apps, schema_editor):
        ChainUp.objects.all().delete()

    dependencies = [
        ('segments', '0005_alter_segment_options_chainup'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainup',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chainup',
            name='next_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(load_fixture, reverse_fixture),
    ]
