# Generated by Django 5.2 on 2026-02-07 00:18

from django.core.management import call_command
from django.db import migrations

from apps.segments.models import ChainUp


class Migration(migrations.Migration):
    def load_fixture(apps, schema_editor):
        call_command('loaddata', 'chainups.json', app_label='segments')

    def reverse_fixture(apps, schema_editor):
        ChainUp.objects.all().delete()

    dependencies = [
        ('segments', '0005_alter_segment_options_chainup'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_fixture),
    ]
