# Generated by Django 5.2 on 2026-02-18 18:41
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('segments', '0005_alter_segment_options_chainup'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainup',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chainup',
            name='next_update',
            field=models.DateTimeField(null=True),
        ),
    ]
