# Generated by Django 5.2 on 2026-02-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0006_auto_20260207_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainup',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chainup',
            name='next_update',
            field=models.DateTimeField(null=True),
        ),
    ]
