# Generated by Django 5.2 on 2026-02-25 21:48
from django.core.management import call_command
from django.db import migrations

from apps.segments.models import ChainUp

class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0006_chainup_active_chainup_next_update"),
        ('organizations', '0007_auto_20260219_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chainup",
            name="active",
        ),
        migrations.RemoveField(
            model_name="chainup",
            name="next_update",
        ),
    ]
