# Generated by Django 5.2 on 2026-02-25 21:48
from django.core.management import call_command
from django.db import migrations

from apps.segments.models import ChainUp

class Migration(migrations.Migration):
    def load_fixture(apps, schema_editor):
        ChainUp.objects.all().delete()
        call_command('loaddata', 'chainups.json', app_label='segments')

    def reverse_fixture(apps, schema_editor):
        ChainUp.objects.all().delete()

    dependencies = [
        ("segments", "0006_chainup_active_chainup_next_update"),
        ('organizations', '0007_auto_20260219_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chainup",
            name="active",
        ),
        migrations.RemoveField(
            model_name="chainup",
            name="next_update",
        ),
        migrations.RunPython(load_fixture, reverse_fixture),
    ]
