# Generated by Django 5.2 on 2026-02-25 21:48
from django.core.management import call_command
from django.db import migrations

from apps.segments.models import ChainUp

class Migration(migrations.Migration):
    def load_fixture(apps, schema_editor):
        ChainUp.objects.all().delete()
        call_command('loaddata', 'chainups.json', app_label='segments')

    def reverse_fixture(apps, schema_editor):
        ChainUp.objects.all().delete()

    dependencies = [
        ("segments", "0007_remove_chainup_active_remove_chainup_next_update"),
        ('events', '0013_event_chainup'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_fixture),
    ]
