# Generated by Django 5.2 on 2026-04-30 23:52
from django.core.management import call_command
from django.db import migrations

def load_fixture(apps, schema_editor):
    call_command('update_segment_names')

def reverse_fixture(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0008_chainup_fixtures"),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_fixture),
    ]
