{{- if and .Values.serviceaccount.enabled (not .Release.IsUpgrade) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
