{{ if .Values.serviceaccount.enabled }}
{{- if not (lookup "rbac.authorization.k8s.io/v1" "Role" .Release.Namespace "read-postgresclusters-metadata") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-postgresclusters-metadata
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - postgres-operator.crunchydata.com
  resources:
  - postgresclusters
  verbs:
  - get
  - list
  - read
{{- end }}
{{- end }}
