{{- if and .Values.serviceaccount.enabled (not .Release.IsUpgrade) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - postgres-operator.crunchydata.com
  resources:
  - postgresclusters
  verbs:
  - get
  - list
  - read
{{- end }}
