{{ if .Values.serviceaccount.enabled }}
{{- if not (lookup "rbac.authorization.k8s.io/v1" "RoleBinding" .Release.Namespace "read-postgresclusters-metadata-users") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-postgresclusters-metadata-users
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-postgresclusters-metadata
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceaccount.name }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}