{{ if .Values.serviceaccount.enabled }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceaccount.name }}
  name: {{ .Values.serviceaccount.name }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/service-account-token
{{ end }}