{{- if and .Values.serviceaccount.enabled (not .Release.IsUpgrade) }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: {{ template "app.fullname" . }}
  name: {{ template "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/service-account-token
{{- end }}
