#!/bin/sh

# Find main files
MAIN=`find /usr/share/nginx/html/assets/index-*.js`
MAINCSS=`find /usr/share/nginx/html/assets/index-*.css`
#MAINSVG=`find /usr/share/nginx/html/*.svg`

# Set the environment to be used for caching django content
sed -i "s~{ENVIRONMENT}~$ENVIRONMENT~g" /etc/nginx/conf.d/default.conf

echo -e "window.API_HOST='${VITE_API_HOST}';" >> $MAIN

#precompress the main js and css files to improve performance
gzip -k $MAIN
gzip -k $MAINCSS
#gzip -k $MAINSVG