#!/bin/sh

# Check if maintenance mode is enabled
if [ "$MAINTENANCE_MODE" = "true" ]; then
    echo "Maintenance mode is enabled. Updating Nginx configuration and skipping the rest of the script..."
    cp /etc/nginx/default_maintenance.txt /etc/nginx/conf.d/default.conf
    # Exit script
    exit 0
fi

# Find main files
MAIN=`find /usr/share/nginx/html/static/js/main.*.js`
MAINCSS=`find /usr/share/nginx/html/static/css/main.*.css`
MAINSVG=`find /usr/share/nginx/html/static/media/*.svg`

# Append environment variables to main JS file
echo -e "window.DEPLOYMENT_TAG='${DEPLOYMENT_TAG}';" >> $MAIN
echo -e "window.RELEASE='${RELEASE:-}';" >> $MAIN

# Set the environment to be used for caching django content
sed -i "s~{ENVIRONMENT}~$ENVIRONMENT~g" /etc/nginx/conf.d/default.conf

# Check if the environment is 'prod' so that we remove the noindex header
if [ "$ENVIRONMENT" = "prod-drivebc" ]; then
    echo "Environment is 'prod' removing X-Robots-Tag noindex header."
    sed -i '/add_header X-Robots-Tag "noindex";/d' /etc/nginx/conf.d/security_headers.conf
else
    echo "Environment is not 'prod', keeping X-Robots-Tag noindex header."
fi

#precompress the main js and css files to improve performance
gzip -k $MAIN
gzip -k $MAINCSS
gzip -k $MAINSVG
