export const API_HOST = `${import.meta.env.VITE_API_HOST}`;
export const GEOCODER_HOST = `${import.meta.env.VITE_GEOCODER_HOST}`;
export const GEOCODER_CLIENT_ID = `${import.meta.env.VITE_GEOCODER_CLIENT_ID}`;
export const ROUTER_CLIENT_ID = `${import.meta.env.VITE_ROUTER_CLIENT_ID}`;
export const DEBUG = `${import.meta.env.VITE_DEBUG}`;
export const BASE_MAP_URL = `${import.meta.env.VITE_BASE_MAP_URL}`;
export const MAP_STYLE_URL = `${import.meta.env.VITE_MAP_STYLE_URL}`;
export const DEPLOYMENT_TAG = `${import.meta.env.VITE_DEPLOYMENT_TAG || ''}`
export const BRANCH = `${import.meta.env.VITE_BRANCH || ''}`
export const RELEASE = `${import.meta.env.VITE_RELEASE || ''}`
export const ALLOW_LOCAL_ACCOUNTS = `${import.meta.env.VITE_ALLOW_LOCAL_ACCOUNTS || ''}`
