# Generated by Django 5.2 on 2026-01-02 23:25

import apps.events.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_contact_id_organization_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='segments',
            field=apps.events.models.OrderedListField(default=list),
        ),
    ]
