# Generated by Django 5.2 on 2026-02-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_servicearea_segments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='contact_id',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, default='', max_length=60, unique=True),
        ),
    ]
