# Generated by Django 5.2 on 2026-02-10 23:39

from django.core.management import call_command
from django.db import migrations

import apps.shared.models
from apps.organizations.models import ServiceArea


class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0005_alter_organization_contact_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='routes',
            field=apps.shared.models.OrderedListField(default=list),
        ),
    ]
