# Generated by Django 5.2 on 2026-02-10 23:39

from django.core.management import call_command
from django.db import migrations

import apps.shared.models
from apps.organizations.models import ServiceArea


class Migration(migrations.Migration):
    def run_mgmt_cmd(apps, schema_editor):
        call_command('update_area_routes')

    def reverse_mgmt_cmd(apps, schema_editor):
        ServiceArea.objects.update(routes=[])

    dependencies = [
        ('organizations', '0005_alter_organization_contact_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='routes',
            field=apps.shared.models.OrderedListField(default=list),
        ),
        migrations.RunPython(run_mgmt_cmd, reverse_mgmt_cmd),
    ]
