# Generated by Django 5.2 on 2026-02-19 01:00
from django.core.management import call_command
from django.db import migrations

from apps.organizations.models import ServiceArea


class Migration(migrations.Migration):
    def load_fixture(apps, schema_editor):
        call_command('loaddata', 'service_areas.json', app_label='organizations')
        call_command('update_area_routes')

    def reverse_fixture(apps, schema_editor):
        ServiceArea.objects.all().delete()

    dependencies = [
        ('organizations', '0006_servicearea_routes'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_fixture),
    ]
