# Generated by Django 5.2 on 2026-06-04 23:52

from django.core.management import call_command
from django.db import migrations


class Migration(migrations.Migration):
    def run_command(apps, schema_editor):
        call_command('fix_area_names')

    def reverse_command(apps, schema_editor):
        pass

    dependencies = [
        ("organizations", "0007_auto_20260219_0100"),
    ]

    operations = [
        migrations.RunPython(run_command, reverse_command),
    ]
