# Generated by Django 5.2.14 on 2026-08-14 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_auto_20260604_2352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicearea',
            options={'ordering': ['sortingOrder']},
        ),
    ]
