# Generated by Django 5.2 on 2026-04-15 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandmarkType',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('code', models.CharField(primary_key=True, serialize=False)),
                ('description', models.CharField()),
                ('notes', models.CharField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
