# Generated by Django 5.2 on 2026-04-15 17:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lki', '0003_changelog_classcategory_latlonsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('version', models.IntegerField()),
                ('number', models.IntegerField()),
                ('code', models.CharField()),
                ('name', models.CharField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lki.classcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
