# Generated by Django 5.2 on 2026-04-15 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lki', '0004_classcharacteristic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('direction', models.CharField()),
                ('search_sequence', models.IntegerField()),
                ('report_sequence', models.IntegerField()),
                ('length', models.FloatField()),
                ('revised', models.DateField(null=True)),
                ('effective', models.DateField(null=True)),
                ('created', models.DateField(null=True)),
                ('road_added', models.DateField(null=True)),
                ('devolved', models.DateField(null=True)),
                ('begin_node', models.CharField()),
                ('begin_continuity', models.CharField()),
                ('begin_km', models.FloatField(null=True)),
                ('end_node', models.CharField()),
                ('end_continuity', models.CharField()),
                ('end_km', models.FloatField(null=True)),
                ('nway', models.IntegerField()),
                ('opposite_segment', models.CharField(blank=True)),
                ('description', models.CharField()),
                ('km_year', models.IntegerField(null=True)),
                ('highways', models.ManyToManyField(to='lki.highway')),
                ('opposite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lki.segment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
