# Generated by Django 5.2 on 2026-04-15 21:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lki', '0005_segment'),
        ('organizations', '0007_auto_20260219_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('start', models.FloatField(default=0.0)),
                ('end', models.FloatField(default=999.9)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.servicearea')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lki.segment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='segment',
            name='areas',
            field=models.ManyToManyField(through='lki.SegmentArea', to='organizations.servicearea'),
        ),
    ]
