# Generated by Django 5.2 on 2026-04-15 21:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lki', '0006_segmentarea_segment_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('start', models.FloatField(default=0.0)),
                ('end', models.FloatField(default=999.9)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lki.classcategory')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lki.classcharacteristic')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lki.segment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
