# Generated by Django 5.2 on 2026-04-15 22:26

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lki', '0007_segmentclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('km', models.FloatField()),
                ('number', models.IntegerField()),
                ('description', models.CharField()),
                ('side', models.CharField(blank=True)),
                ('point', models.CharField(blank=True)),
                ('ext_id', models.CharField(blank=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('km_post', models.FloatField(null=True)),
                ('landmark_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lki.landmarktype')),
                ('segment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lki.segment')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lki.latlonsource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
