# Generated by Django 5.2 on 2026-04-16 00:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lki', '0008_landmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('legs', models.IntegerField()),
                ('legs_confirmed', models.BooleanField()),
                ('road1', models.CharField()),
                ('road2', models.CharField()),
                ('road3', models.CharField(blank=True)),
                ('place', models.CharField(blank=True)),
                ('year_signalized', models.IntegerField(null=True)),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intersections', to='lki.landmark')),
                ('landmarks', models.ManyToManyField(to='lki.landmark')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
