# Generated by Django 5.2 on 2026-04-24 17:52

from django.db import migrations
from django.core.management import call_command

class Migration(migrations.Migration):

    def load_fixture(apps, schema_editor):
        call_command('loaddata', 'lki.json', app_label='lki')

    def reverse_fixture(apps, schema_editor):
        pass

    dependencies = [
        ('lki', '0009_intersection'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_fixture)
    ]
