# Generated by Django 6.0 on 2026-07-24 16:22

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lki', '0010_load_fixture'),
        ('organizations', '0008_auto_20260604_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intersection',
            name='landmark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourced_intersection', to='lki.landmark'),
        ),
        migrations.CreateModel(
            name='Crossroad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('route', models.CharField()),
                ('km_from_start', models.FloatField()),
                ('locality', models.CharField(blank=True)),
                ('name', models.CharField()),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('service_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.servicearea')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
