# Generated by Django 5.2 on 2025-11-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideuser',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='users', to='organizations.organization'),
        ),
    ]
