# Generated by Django 5.2 on 2026-01-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rideuser_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
