# Generated by Django 5.2 on 2026-02-27 19:25

from django.core.management import call_command
from django.db import migrations


class Migration(migrations.Migration):
    def load_dit_users(apps, schema_editor):
        call_command('import_dit_users')

    def reverse_dit_users(apps, schema_editor):
        pass  # intentionally blank to avoid dangerous operation, users and orgs can be cleared manually

    dependencies = [
        ("users", "0003_rideuser_phone_number"),
    ]

    operations = [
        migrations.RunPython(load_dit_users, reverse_dit_users),
    ]
