# Generated by Django 5.2.14 on 2026-08-31 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_create_task_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rideuser',
            options={'permissions': [('approve_ride_events', 'Can approve RIDE events'), ('access_camera_page', 'Can access camera page'), ('administer_cameras', 'Can manage cameras')]},
        ),
    ]
