# Generated by Django 5.2.14 on 2026-08-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='visible',
            field=models.BooleanField(default=True, help_text='Whether this camera is visible to DriveBC users.'),
        ),
    ]
