# Generated by Django 5.2.14 on 2026-09-11 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='installed',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='camera',
            name='last_inspected',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
