# Generated by Django 5.2.14 on 2026-08-10 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='camera',
            table=None,
        ),
    ]
