# Generated by Django 5.2.14 on 2026-09-11 17:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_camera_installed_camera_last_inspected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='installed',
            new_name='camera_installed',
        ),
        migrations.RenameField(
            model_name='camera',
            old_name='last_inspected',
            new_name='camera_last_inspected',
        ),
        migrations.AddField(
            model_name='camera',
            name='modem_installed',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
