# Generated by Django 5.2.14 on 2026-08-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_alter_camera_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='locations_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
