# Generated by Django 5.2.14 on 2026-09-11 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_rename_installed_camera_camera_installed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='camera_installed',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='camera_last_inspected',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='modem_installed',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
