# Generated by Django 5.2.14 on 2026-08-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_cameralog'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cameralog',
            table=None,
        ),
    ]
