# Generated by Django 5.2.14 on 2026-08-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_cameramake_cameratype_camera_camera_make_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='locations_elevation',
            field=models.FloatField(blank=True, null=True, verbose_name='Elevation (metres)'),
        ),
        migrations.AddField(
            model_name='camera',
            name='locations_geo_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='camera',
            name='locations_geo_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
