# Generated by Django 5.2.14 on 2026-08-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_camera_locations_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='internet_inset_horizontal',
            field=models.BooleanField(default=False),
        ),
    ]
