# Generated by Django 5.2.14 on 2026-08-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_camera_locations_elevation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='cam_internet_credit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='cam_internet_website_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='image_watermark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
