# Generated by Django 5.2.14 on 2026-08-13 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_alter_camera_internet_inset_horizontal'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='ccp_camera_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='ccp_camera_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CameraView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('orientation', models.CharField(choices=[('NORTH', 'North'), ('SOUTH', 'South'), ('EAST', 'East'), ('WEST', 'West'), ('NORTHEAST', 'Northeast'), ('NORTHWEST', 'Northwest'), ('SOUTHEAST', 'Southeast'), ('SOUTHWEST', 'Southwest')], max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_name', models.CharField(blank=True, max_length=255, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='cameras.camera')),
            ],
        ),
    ]
