# Generated by Django 5.2.14 on 2026-09-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_alter_camera_camera_installed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='baud_rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='camera',
            name='on_demand',
            field=models.BooleanField(default=False, help_text='Whether this camera is on demand.'),
        ),
        migrations.AddField(
            model_name='camera',
            name='password',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='camera',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='camera',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='camera',
            name='update_frequency',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='username',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
