# Generated by Django 5.2.14 on 2026-08-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_alter_cameralog_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
