# Generated by Django 5.2.14 on 2026-08-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0005_camera_cam_internet_credit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='cam_internet_credit',
            new_name='camera_credit',
        ),
        migrations.RenameField(
            model_name='camera',
            old_name='cam_internet_website_url',
            new_name='camera_credit_url',
        ),
    ]
