# Generated by Django 5.2.14 on 2026-08-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0005_camera_ccp_camera_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='ccp_camera_highway',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
