# Generated by Django 5.2.14 on 2026-09-14 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0006_camera_supply_serial_camera_supply_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraview',
            name='last_update_attempt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='cameraview',
            name='last_update_modified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
