# Generated by Django 5.2.14 on 2026-08-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0006_antenna_display_order_businessarea_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionprotocol',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='connectiontype',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='powersource',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='road',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
