# Generated by Django 5.2.14 on 2026-08-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0006_rename_cam_internet_credit_camera_camera_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='marked_delayed',
            field=models.BooleanField(default=True, help_text='Whether this camera is marked delayed.'),
        ),
    ]
