# Generated by Django 5.2.14 on 2026-08-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0006_camera_ccp_camera_highway'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraview',
            name='is_on',
            field=models.BooleanField(default=True),
        ),
    ]
