# Generated by Django 5.2.14 on 2026-09-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0007_cameraview_last_update_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='connection_ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address for FTP/pull connections', null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='connection_port',
            field=models.PositiveIntegerField(blank=True, help_text='Port for FTP/pull connections', null=True),
        ),
    ]
