# Generated by Django 5.2.14 on 2026-08-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0007_cameraview_is_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraview',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
