# Generated by Django 5.2.14 on 2026-08-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0007_camera_marked_delayed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='marked_delayed',
            field=models.BooleanField(default=False, help_text='Whether this camera is marked delayed.'),
        ),
    ]
