# Generated by Django 5.2.14 on 2026-08-13 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0008_cameraview_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='internet_name',
        ),
    ]
