# Generated by Django 5.2.14 on 2026-09-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0008_camera_connection_ip_address_camera_connection_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraview',
            name='orientation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
