# Generated by Django 5.2.14 on 2026-09-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0009_alter_cameraview_orientation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraDefaultMessaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disabled_reason_default', models.CharField(blank=True, default='', help_text='Reason for disabling view', max_length=255)),
                ('disabled_short_description', models.CharField(blank=True, default='', help_text='Short description for disabled view', max_length=255)),
                ('disabled_long_description', models.TextField(blank=True, default='', help_text='Long description for disabled view')),
            ],
            options={
                'verbose_name': 'Default messaging',
                'verbose_name_plural': 'Default messaging',
            },
        ),
    ]
