# Generated by Django 5.2.14 on 2026-08-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0009_remove_camera_internet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='ccp_region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
