# Generated by Django 5.2.14 on 2026-08-14 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0010_camera_ccp_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antenna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gain_dbi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommunicationDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommunicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConnectionProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConnectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElectricalContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PowerSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, help_text='e.g. Hwy 1, Hwy 99', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Road / Highway',
                'verbose_name_plural': 'Roads & Highways',
            },
        ),
        migrations.CreateModel(
            name='RoadMaintenanceContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='camera',
            name='internet_caption',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='internet_comments',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='internet_contact_notes',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='internet_credit',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='internet_dbc_mark',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='internet_display_filename',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='internet_display_folder',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='internet_drivebc_url',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='internet_ftp_filename',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='internet_ftp_folder',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='internet_ftp_path',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='internet_getfile2_url',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='internet_inset_horizontal',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='internet_last_updated',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='internet_updated_by',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='internet_website_url',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='locations_albers_easting',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='locations_albers_northing',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='locations_business_area',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='locations_cam_group',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='locations_crossroad',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='locations_dd',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='locations_description',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='locations_elevation',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='locations_forecast_id',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='locations_geo_latitude',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='locations_geo_longitude',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='locations_highway',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='locations_highway_section',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='locations_landmark',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='locations_last_updated',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='locations_lrs_node',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='locations_map_art_no',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='locations_orientation',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='locations_region',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='locations_regional_map_url',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='locations_segment',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='locations_thumbnail_map_url',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='locations_updated_by',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='locations_weather_station',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_alternate_owner',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_antennae',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_asset_no',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_baud_rate',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_camera_make',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_comm_device',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_comm_tech',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_credentials',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_day_implemented',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_day_installed',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_day_modem',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_hardware_notes',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_link_check',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_local_ip',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_maint_notes',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_modem_esn',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_modem_ip',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_modem_phone',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_month_implemented',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_month_installed',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_month_modem',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_msl',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_notes',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_owner',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_ps_sn',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_public_ip',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_service_provider',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_signal',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_signal_strength',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_sn',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_upload_image',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_uploads_every',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_year_implemented',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_year_installed',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='maintenance_year_modem',
        ),
        migrations.AddField(
            model_name='camera',
            name='antenna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='cameras.antenna'),
        ),
        migrations.AddField(
            model_name='camera',
            name='business_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='cameras.businessarea'),
        ),
        migrations.AddField(
            model_name='camera',
            name='communication_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='cameras.communicationdevice'),
        ),
        migrations.AddField(
            model_name='camera',
            name='communication_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='cameras.communicationtype'),
        ),
        migrations.AddField(
            model_name='camera',
            name='connection_protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='cameras.connectionprotocol'),
        ),
        migrations.AddField(
            model_name='camera',
            name='connection_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='cameras.connectiontype'),
        ),
        migrations.AddField(
            model_name='camera',
            name='electrical_contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='cameras.electricalcontractor'),
        ),
        migrations.AddField(
            model_name='camera',
            name='power_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='cameras.powersource'),
        ),
        migrations.AddField(
            model_name='camera',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='cameras.region'),
        ),
        migrations.AddField(
            model_name='camera',
            name='road',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='cameras.road', verbose_name='Road / Highway'),
        ),
        migrations.AddField(
            model_name='camera',
            name='road_maintenance_contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='cameras.roadmaintenancecontractor'),
        ),
        migrations.AddField(
            model_name='camera',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='cameras.serviceprovider'),
        ),
    ]
