# Generated by Django 5.2.16 on 2026-09-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0010_cameradefaultmessaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='display_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
