# Generated by Django 5.2.16 on 2026-09-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0011_camera_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='mac_address',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camera',
            name='password',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camera',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camera',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camera',
            name='supply_serial',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camera',
            name='supply_type',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camera',
            name='username',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
