# Generated by Django 5.2.16 on 2026-09-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0012_alter_camera_mac_address_alter_camera_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='baud_rate',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
