# This workflow is to update Crunchy using Github actions

name: Crunchy DB Update

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
      cluster:
        type: choice
        description: OpenShift Cluster
        options: 
        - gold
        - golddr

jobs:
  update-openshift:
    runs-on: ubuntu-latest
    name: Deploy Latest Helm Chart to ${{ github.event.inputs.cluster }} on ${{ github.event.inputs.environment }}
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
    - name: Select OpenShift Server and Token
      run: |
        if [[ "${{ github.event.inputs.cluster }}" == "gold" ]]; then
          echo "SERVER=${{ vars.OPENSHIFT_GOLD_SERVER }}" >> $GITHUB_ENV
          echo "TOKEN=${{ vars.OPENSHIFT_GOLD_TOKEN }}" >> $GITHUB_ENV
        else
          echo "SERVER=${{ vars.OPENSHIFT_GOLDDR_SERVER }}" >> $GITHUB_ENV
          echo "TOKEN=${{ secrets.OPENSHIFT_GOLDDR_TOKEN }}" >> $GITHUB_ENV
        fi

    - name: Checkout code
      uses: actions/checkout@v4 

    - name: Install CLI tools from OpenShift Mirror
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: "4"
          
    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ env.SERVER }}
        openshift_token: ${{ env.TOKEN }}
        namespace: ${{ vars.OPENSHIFT_NAMESPACE }}
        insecure_skip_tls_verify: true

    - name: Helm upgrade on OpenShift ${{ github.event.inputs.environment }} Environment
      run: |
        helm upgrade ${{ github.event.inputs.environment }}-ride-db -f ./infrastructure/crunchy-postgres/values-${{ github.event.inputs.environment }}-${{ github.event.inputs.cluster }}.yaml ./infrastructure/crunchy-postgres  --set crunchy.pgbackRest.s3.bucket=${{ secrets.CRUNCHY_BUCKET }} --set crunchy.pgbackrest.s3.endpoint=${{ secrets.CRUNCHY_ENDPOINT }}

