# This workflow is to update the GSLB Monitoring Pods using Github actions.

name: Build standbycheck

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
      cluster:
        type: choice
        description: OpenShift Cluster
        options: 
        - gold
        - golddr


# Based on: https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images

env:
  REGISTRY: ghcr.io
  STANDBY_IMAGE_NAME: ${{ github.repository }}-standbycheck

jobs:
  build-and-push-standbycheck:
    runs-on: ubuntu-latest
    name: Build & Push standbycheck Image
    environment: dev
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.STANDBY_IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=long

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./compose/standbycheck/
          file: ./compose/standbycheck/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args:
            DEBUG_BUILD=true

  update-openshift:
    runs-on: ubuntu-latest
    name: Deploy Latest Helm Chart to ${{ github.event.inputs.cluster }} on ${{ github.event.inputs.environment }}
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 

    - name: Install CLI tools from OpenShift Mirror
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: "4"
          
    - name: Authenticate and set context for Gold
      if: ${{ github.event.inputs.cluster == 'gold' }}
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ vars.OPENSHIFT_GOLD_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_GOLD_TOKEN }}
        namespace: ${{ vars.OPENSHIFT_NAMESPACE }}
        insecure_skip_tls_verify: true

    - name: Helm upgrade on OpenShift ${{ github.event.inputs.environment }} Environment
      run: |
#        helm upgrade ${{ github.event.inputs.environment }}-ride-db -f ./infrastructure/crunchy-postgres/values-${{ github.event.inputs.environment }}-${{ github.event.inputs.cluster }}.yaml ./infrastructure/crunchy-postgres  --set crunchy.pgBackRest.s3.bucket=${{ secrets.CRUNCHY_BUCKET }} --set crunchy.pgBackRest.s3.endpoint=${{ secrets.CRUNCHY_ENDPOINT }}


    - name: Authenticate and set context for GoldDR
      if: ${{ github.event.inputs.cluster == 'golddr' }}
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ vars.OPENSHIFT_GOLDDR_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_GOLDDR_TOKEN }}
        namespace: ${{ vars.OPENSHIFT_NAMESPACE }}
        insecure_skip_tls_verify: true

    - name: Helm upgrade on OpenShift ${{ github.event.inputs.environment }} Environment
      run: |
#        helm upgrade ${{ github.event.inputs.environment }}-ride-db -f ./infrastructure/crunchy-postgres/values-${{ github.event.inputs.environment }}-gold.yaml -f ./infrastructure/crunchy-postgres/values-${{ github.event.inputs.environment }}-golddr.yaml ./infrastructure/crunchy-postgres  --set crunchy.pgBackRest.s3.bucket=${{ secrets.CRUNCHY_BUCKET }} --set crunchy.pgBackRest.s3.endpoint=${{ secrets.CRUNCHY_ENDPOINT }}

