name: 2. Build & Deploy to Test

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  WEBAPP_IMAGE_NAME: ${{ github.repository }}-webapp

jobs:
  tag:
    runs-on: ubuntu-latest
    name: Create Tag and set Variable
    permissions:
        contents: write
    outputs:
      tag: ${{ steps.create_tag.outputs.tag }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate Date-Time Tag
      id: generate_tag
      run: |
        TAG=$(date +"%Y%m%d-%H%M%S")
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Create Tag
      id: create_tag
      if: github.event_name == 'workflow_dispatch'
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git tag ${{ steps.generate_tag.outputs.tag }}
        git push origin ${{ steps.generate_tag.outputs.tag }}
        echo "tag=${{ steps.generate_tag.outputs.tag }}" >> $GITHUB_OUTPUT

    - name: Display Tag Name
      run: |
        echo "Tag Name: ${{ steps.create_tag.outputs.tag }}"




