# Generated by Django 5.2 on 2025-09-05 21:41

import apps.events.models
import django.contrib.gis.db.models.fields
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id', models.CharField(blank=True, max_length=20, null=True)),
                ('version', models.IntegerField(default=0)),
                ('latest', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['id', 'version'],
                'get_latest_by': ['id', 'version'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id', models.CharField(blank=True, max_length=20, null=True)),
                ('version', models.IntegerField(default=0)),
                ('latest', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('meta', models.JSONField(default=dict)),
                ('event_type', models.CharField(blank=True, null=True)),
                ('status', models.CharField(default='Active')),
                ('start', apps.events.models.LocationField(default=dict)),
                ('end', apps.events.models.LocationField(default=dict, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=4326)),
                ('direction', models.CharField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, null=True)),
                ('category', models.CharField(blank=True, null=True)),
                ('situation', models.PositiveIntegerField(default=0)),
                ('impacts', apps.events.models.OrderedListField()),
                ('restrictions', apps.events.models.OrderedListField()),
                ('conditions', apps.events.models.OrderedListField()),
                ('delay_amount', models.PositiveIntegerField(default=0)),
                ('delay_unit', models.CharField(default='minutes')),
                ('next_update', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('additional', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id', 'version'],
                'get_latest_by': ['id', 'version'],
                'abstract': False,
            },
        ),
    ]
