# Generated by Django 5.2 on 2025-09-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Note',
        ),
    ]
