# Generated by Django 5.2 on 2025-04-29 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='current',
            new_name='latest',
        ),
    ]
