# Generated by Django 5.2 on 2025-09-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_comment_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='event',
            field=models.CharField(default='asdf'),
            preserve_default=False,
        ),
    ]
