# Generated by Django 5.2 on 2025-04-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_current_event_latest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['id', 'version']},
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('id', 'version'), name='id_version'),
        ),
    ]
