# Generated by Django 5.2 on 2025-10-23 21:27

import apps.events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_trafficimpact'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='schedules',
            field=apps.events.models.OrderedListField(default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='conditions',
            field=apps.events.models.OrderedListField(default=list),
        ),
        migrations.AlterField(
            model_name='event',
            name='impacts',
            field=apps.events.models.OrderedListField(default=list),
        ),
        migrations.AlterField(
            model_name='event',
            name='restrictions',
            field=apps.events.models.OrderedListField(default=list),
        ),
    ]
