# Generated by Django 5.2 on 2025-11-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_schedules_event_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
