# Generated by Django 5.2 on 2025-12-09 18:53

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_user_alter_note_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('pending', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='latest_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
