# Generated by Django 5.2 on 2026-01-06 00:20

import django.db.models.deletion
import django.utils.timezone
from django.core.management import call_command
from django.db import migrations
from django.db import models

from apps.events.models import TrafficImpact, Condition


class Migration(migrations.Migration):
    def load_references(apps, schema_editor):
        call_command('load_references')

    def reverse_references(apps, schema_editor):
        TrafficImpact.objects.all().delete()
        Condition.objects.all().delete()

    dependencies = [
        ('events', '0009_alter_event_managers_event_latest_approved_and_more'),
        ('segments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('label', models.CharField()),
                ('order', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='segments.segment'),
        ),
        migrations.RunPython(load_references, reverse_references),
    ]
