# Generated by Django 5.2 on 2026-01-27 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_condition_alter_event_managers_event_segment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='segment',
        ),
    ]
