# Generated by Django 5.2 on 2026-01-27 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_event_segment'),
        ('segments', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='segments.segment'),
        ),
    ]
