# Generated by Django 5.2 on 2026-03-06 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_chainup'),
        ('organizations', '0007_auto_20260219_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='service_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.servicearea'),
        ),
    ]
