# Generated by Django 5.2 on 2026-03-06 22:44

from django.db import migrations, models
from django.contrib.gis.geos import Point

from apps.events.models import Event
from apps.organizations.models import ServiceArea

def update_service_areas(apps, schema_editor):

    for event in Event.objects.filter(service_area=None):
        try:
            cc = event.start.get('coords')
            if cc is None:
                continue
            point = Point(cc[0], cc[1])
            sa = ServiceArea.objects.filter(geometry__contains=point).first()
            if sa is not None:
                event.service_area = sa
                # does not create a new version
                event.save(force_update=True)
        except Exception as e:
            print(f'Exception getting service area for {event.id}')

def remove_update(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_service_area'),
        ('organizations', '0007_auto_20260219_0100'),
    ]

    operations = [
        migrations.RunPython(update_service_areas, reverse_code=remove_update)
   ]
