# Generated by Django 5.2 on 2026-03-19 21:51
from django.core.management import call_command

import apps.events.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models

from apps.events.models import RouteGeometry


class Migration(migrations.Migration):
    def build_hwy_geometries(apps, schema_editor):
        call_command('build_route_geometries')

    def reverse_hwy_geometries(apps, schema_editor):
        RouteGeometry.objects.all().delete()

    dependencies = [
        ("events", "0015_populate_event_service_areas"),
    ]

    operations = [
        migrations.CreateModel(
            name="RouteGeometry",
            fields=[
                (
                    "id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                (
                    "routes",
                    django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326),
                ),
            ],
        ),
        migrations.AlterModelManagers(
            name="event",
            managers=[
                ("objects", apps.events.models.EverythingManager()),
                ("current", apps.events.models.LatestApprovedManager()),
                ("pending", apps.events.models.PendingManager()),
            ],
        ),
        migrations.RunPython(build_hwy_geometries, reverse_hwy_geometries),
    ]
