# Generated by Django 5.2 on 2026-03-19 22:10

from django.contrib.gis.geos import LineString, Point
from django.db import migrations, models


class Migration(migrations.Migration):
    def build_event_projections(apps, schema_editor):
        Event = apps.get_model("events", "Event")
        for event in Event._default_manager.all():
            event.save()

    def reverse_event_projections(apps, schema_editor):
        # Do nothing on reverse, admins should delete data manually if needed
        pass

    dependencies = [
        ("events", "0016_routegeometry_alter_event_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="route_projection",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.RunPython(build_event_projections, reverse_event_projections),
    ]
