# Generated by Django 5.2 on 2026-03-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0017_event_route_projection"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="from_bulk",
            field=models.BooleanField(default=False),
        ),
    ]
