# Generated by Django 5.2 on 2026-06-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_event_from_bulk'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='last_inactivated',
            field=models.DateTimeField(null=True),
        ),
    ]
