# Generated by Django 5.2 on 2026-02-19 01:00
from django.core.management import call_command
from django.db import migrations
from ..models import Event

from apps.organizations.models import ServiceArea


class Migration(migrations.Migration):
    def update(apps, schema_editor):
        '''
        Populate last_inactivated field for events.

        When the status switches from Active to Inactive, copy last_updated into
        last_inactivated so that the timestamp of the change is captured for
        querying; when the status switches from Inactive to Active, null the
        last_inactivated field so that Active records aren't caught in queries
        for cleared events.

        When an event has multiple versions in a row, all inactive, propagate
        the first last_inactivated timestamp forward so the value is available
        for the event that is also marked latest or latest_approved.

        Note use of update_fields to limit change to last_inactivated field
        (which is populated from last_updated), to avoid changing last_updated
        while running migration.
        '''
        ids = Event.objects.distinct('id').values_list('id', flat=True).order_by('id')
        for id in ids:
            prev = 'Active'
            prevDate = None
            for event in Event.objects.filter(id=id).order_by('version'):
                if event.status == 'Inactive' and prev == 'Active':
                    event.last_inactivated = event.last_updated
                    prevDate = event.last_updated
                    Event.objects.filter(pk=event.pk).update(last_inactivated=event.last_updated)
                elif event.status == 'Active' and prev == 'Inactive':
                    event.last_inactivated = None
                    prevDate = None
                    Event.objects.filter(pk=event.pk).update(last_inactivated=None)
                elif prev == 'Inactive' and event.status == 'Inactive':
                    event.last_inactivated = prevDate
                    Event.objects.filter(pk=event.pk).update(last_inactivated=prevDate)
                prev = event.status

    def reverse(apps, schema_editor):
        Event.objects.update(last_inactivated=None)

    dependencies = [
        ('events', '0019_event_last_inactivated'),
    ]

    operations = [
        migrations.RunPython(update, reverse),
    ]
