# Generated by Django 5.2.14 on 2026-06-19 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0019_event_description_ivr_polygon"),
        ("events", "0020_update_last_inactivated"),
    ]

    operations = []
