# Generated by Django 6.0 on 2026-08-21 22:41

import apps.events.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_update_last_inactivated'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('objects', apps.events.models.EverythingManager()),
                ('current', apps.events.models.LatestApprovedManager()),
                ('pending', apps.events.models.PendingManager()),
                ('relevant', apps.events.models.RelevantManager()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='tlids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list),
        ),
    ]
