# Generated by Django 5.2.14 on 2026-08-14 19:18

import apps.events.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_update_last_inactivated'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('objects', apps.events.models.EverythingManager()),
                ('current', apps.events.models.LatestApprovedManager()),
                ('pending', apps.events.models.PendingManager()),
                ('relevant', apps.events.models.RelevantManager()),
            ],
        ),
    ]
